/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.zi_jing.tsrg2srg;

import net.minecraftforge.gradle.common.util.MappingFile;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        while(true) {
            System.out.println("\nEnter the path of the TSRG file or type \"exit\" to exit...");
            String input = scanner.nextLine();
            if (input.equals("exit"))
                break;
            File tsrgFile = new File(input);
            if (!tsrgFile.exists() || !tsrgFile.isFile()) {
                System.out.println("No such file, please try again.");
                continue;
            }
            System.out.println("Loading " + input);
            MappingFile mappingFile;
            try {
                mappingFile = MappingFile.load(tsrgFile);
            } catch (IOException e) {
                System.out.println("Error while loading TSRG file");
                e.printStackTrace();
                System.out.println();
                continue;
            }
            File outputFile = new File(input + ".srg");
            System.out.println("Writing " + outputFile.getPath());
            try {
                mappingFile.write(MappingFile.Format.SRG, outputFile);
            } catch (IOException e) {
                System.out.println("Error while writing SRG file");
                e.printStackTrace();
                System.out.println();
                continue;
            }
            System.out.println("\nComplete!");
        }

        scanner.close();
    }
}
